branch-defaults:
  master:
    environment: Andromeda-dev
global:
  application_name: Andromeda
  branch: null
  default_platform: Python 3.6
  default_region: us-east-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application

